name: mae_panel
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.12.0
  - torchvision=0.13.0
  - pytorch-cuda=11.8
  - scikit-image=0.21.0
  - tqdm=4.64.1
  - matplotlib
  - seaborn
  - pip
  - pip:
    - notebook
    - pytorch-lightning==1.7.7
    - torchmetrics==0.11.0
    - einops==0.6.0
    - vit-pytorch==0.40.2
